/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApplicationCheckIcon: typeof import('./src/shared/components/icons/ApplicationCheckIcon.vue')['default']
    AuthForm: typeof import('./src/modules/auth/components/AuthForm.vue')['default']
    AuthRequestForm: typeof import('./src/modules/auth/components/AuthRequestForm.vue')['default']
    BaseButton: typeof import('./src/shared/components/ui/button/BaseButton.vue')['default']
    BaseButtonFlat: typeof import('./src/shared/components/ui/button/BaseButtonFlat.vue')['default']
    BaseTitle: typeof import('./src/shared/components/ui/BaseTitle.vue')['default']
    GoodsIcon: typeof import('./src/shared/components/icons/GoodsIcon.vue')['default']
    LogoIcon: typeof import('./src/shared/components/icons/LogoIcon.vue')['default']
    PasswordInput: typeof import('./src/shared/components/ui/input/PasswordInput.vue')['default']
    PhoneInput: typeof import('./src/shared/components/ui/input/PhoneInput.vue')['default']
    ProfileIcon: typeof import('./src/shared/components/icons/ProfileIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/shared/components/SvgIcon.vue')['default']
    TheFooter: typeof import('./src/shared/components/TheFooter.vue')['default']
  }
}
