/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/modules/auth/components/AuthForm.vue')['default']
    AuthRequestForm: typeof import('./src/modules/auth/components/AuthRequestForm.vue')['default']
    BaseButton: typeof import('./src/shared/components/UI/button/BaseButton.vue')['default']
    BaseButtonFlat: typeof import('./src/shared/components/UI/button/BaseButtonFlat.vue')['default']
    LogoIcon: typeof import('./src/shared/components/icons/LogoIcon.vue')['default']
    PasswordInput: typeof import('./src/shared/components/PasswordInput.vue')['default']
    PhoneInput: typeof import('./src/shared/components/PhoneInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
